TestTask1/force-app/main/default/objects/Opportunity_Notification__c/Opportunity_Notification__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Opportunity Notification</label>
</CustomObject>

TestTask1/force-app/main/default/objects/Opportunity_Notification__c/fields/Critical_Amount__c.field-meta.xml
<CustomField>
    <fullName>Critical_Amount__c</fullName>
    <description>Specify opportunity amount for managers notification</description>
    <inlineHelpText>If amount lesser than specified notifications aren&apos;t sent after opportunity update</inlineHelpText>
    <label>Critical Amount For Notification</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

TestTask1/force-app/main/default/objects/Opportunity_Notification__c/fields/Opportunity_StageName__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_StageName__c</fullName>
    <description>Specify opportunity stage name for notification</description>
    <inlineHelpText>If opportunity stage name is updated to specified value and opportunity amount equals or greater than specified in &quot;Critical Amount&quot; field managers of the user are notified</inlineHelpText>
    <label>Opportunity StageName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TestTask1/force-app/main/default/objects/Opportunity_Notification__c/fields/User_Role_for_email_notification__c.field-meta.xml
<CustomField>
    <fullName>User_Role_for_email_notification__c</fullName>
    <description>User Role for email notification and record sharing</description>
    <inlineHelpText>Specify User Role of the users to whom edit access to the record should be granted and email notification should be sent when opportunity amount and stage meet conditions specified above</inlineHelpText>
    <label>User Role for email notification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TestTask1/force-app/main/default/classes/OpportunityNotificationConfig.cls
/** description: This class is used as a default config storege to define opportunity stage and amount which trigger notification and sharings
    */

public with sharing class OpportunityNotificationConfig {
    private static final Integer DEFAULT_CRITICAL_AMOUNT = 10000;
    private static final String DEFAULT_STAGENAME = 'Needs Analysis';
    private static final String DEFAULT_USER_ROLE = 'Chief Manager';
    private static final String DEFAULT_NOTIFICATION_TYPE_NAME = 'Opportunity_Needs_Analisys';
    private static Opportunity_Notification__c notificationCustomSettings = Opportunity_Notification__c.getOrgDefaults();
    private static CustomNotificationType notificationType;
    private static Id defaultUserRoleId;

    public static Integer getCriticalAmount() {
        if (notificationCustomSettings.Critical_Amount__c == null) {
            return DEFAULT_CRITICAL_AMOUNT;
        }
        return Integer.ValueOf(notificationCustomSettings.Critical_Amount__c);
    }

    public static String getCriticalStage() {
        if (notificationCustomSettings.Opportunity_StageName__c == null) {
            return DEFAULT_STAGENAME;
        }
        return notificationCustomSettings.Opportunity_StageName__c;
    }

    public static String getUserRole() {
        if (notificationCustomSettings.User_Role_for_email_notification__c == null) {
            return DEFAULT_USER_ROLE;
        }
        return notificationCustomSettings.User_Role_for_email_notification__c;
    }

    public static Id getUserRoleIdToNotify() {
        if(defaultUserRoleId == null) {
            List<UserRole> roles = [SELECT Id FROM UserRole WHERE Name = :DEFAULT_USER_ROLE];
            if(!roles.isEmpty()) {
                defaultUserRoleId = roles.get(0).Id;
            } 
        }
        return defaultUserRoleId;
    }

    public static CustomNotificationType getNotificationType() {
        if(notificationType == null) {
            notificationType = [SELECT Id, MasterLabel, Description, DeveloperName FROM CustomNotificationType WHERE DeveloperName = :DEFAULT_NOTIFICATION_TYPE_NAME];
        }
        return notificationType;
    }

}